### ISSUE TITLE
Options field implementation incorrect

### ISSUE THREAD

**Issue by ssimo3lsuhsc** [BernhardBaumrock/RockFinder#5]
You claim to have implemented the Options field by the same semantics as File field. WRONG. The representation of Options fields in ProcessWire 3.0, released in early 2019, must be more robust than they ever were in ProcessWire 2.x, but I don't know, seeing as I've never used 2.x. In ProcessWire 3.0, the titles and values of ALL Options fields are stored in the table "fieldtype_options" table, with the "option_id" as the primary key and with the "data" field of the individual Options field tables as foreign keys to this table. If the user is running ProcessWire 3.0, then the SQL that will generate the proper output of a single-select Options field, with `$fieldname` as the field name and `$page` as the page, is as follows:

```
SELECT
#value might be null if no pipeline or might be the empty string
CASE WHEN value IS NULL OR VALUE = '' THEN title ELSE value END AS $fieldname
FROM fieldtype_options
WHERE option_id = (
SELECT data FROM field_$fieldname WHERE pages_id = {$page->id}
)
```

I have not investigated multiple-select Options fields, but I expect that they are something similar.

Thank you!

Stuart Simon

**Comment by BernhardBaumrock** [comment]
Hi Stuart,
thx for your contribution. Could you please provide a step by step guide what I have to do to reproduce the issue? What would be the expected behaviour? What is the actual behaviour? What is your finder code?
Thx

**Comment by ssimo3lsuhsc** [comment]
I'll have to set up a "toy" version of my site to produce what I was testing. For a while, I had been contenting myself with Page Reference fields, but **they don't allow default values.** If I weren't so intimidated by the idea of unit testing, I'd submit a PR with a new class to handle options fields. As it stands, no tutorial about unit testing can teach me anything practical because I'm not sure what assertions I can make, and whether they are logically equivalent to the expected outcome.

**Comment by ssimo3lsuhsc** [comment]
To reproduce this issue under a fresh installation of ProcessWire 3.0, do the following:

1. Create two new templates in the source, page-with-option.php and page**s**-with-option.php. The template for page-with-option.php is irrelevant, but the code for page**s**-with-option.php is:
```
<?php
namespace ProcessWire;

$optionsAverageFinder = new RockFinder("parent=$page", ["option1"]);
$optionsAverageSql = $optionsAverageFinder-> getSQL();
$optionsAverageFinder->sql = "SELECT AVG(option1) AS optionsAverage FROM ($optionsAverageSql) AS tmp;";
echo "<p>Average from straight declaration of array: " . $optionsAverageFinder->getArrays()[0]["optionsAverage"] . "</p>";
echo "<p>SQL from straight declation of array:" . $optionsAverageFinder->getSQL() . "</p>";

$optionsAverageFinder = new RockFinder("parent=$page");
$optionsAverageFinder->addField("option1", ["value"]);
$optionsAverageSql = $optionsAverageFinder->getSQL();
$optionsAverageFinder->sql = "SELECT AVG(`option1:value`) AS optionsAverage FROM ($optionsAverageSql) AS tmp;";
echo "<p>Average from addField: " . $optionsAverageFinder->getArrays()[0]["optionsAverage"] . "</p>";
echo "<p>SQL from addField: " . $optionsAverageFinder->getSQL() . "</p>";
```
2. Add both templates to ProcessWire.
3. Add a Select Options field to ProcessWire named option 1 and with the following values:
0|Zero
2|Two

4. Add your newly created Field to the field list of the page-with-option template.
5. Add a page**s**-with-option to your site.
6. Add two page-with-option as children to the page created in Step 5. The first option1 should be set as "Zero," the second as "2."
7. View your page**s**-with option. You should see the following:
![Pages with Option](https://user-images.githubusercontent.com/20207672/57950404-bd785a00-78ac-11e9-801c-44c47cd5f889.png)

The first average shown is 1.5, which is correct if the options' primary keys are 1 and 2, respectively. But they have the _values_ 0 and 2, so the correct average is 1.

**Comment by ssimo3lsuhsc** [comment]
I now see that in the fieldtype_option table the fields_id and option_id are coprimary so that multiple options fields could have an option with an option_id of 1. Still, it is IMPERATIVE that we add the extra join to fully support options fields because as it stands they will only ever amount to positive integers. What if we want the value of 0 from them? What if we want text?

**Comment by flipzoom** [comment]
Hey @BernhardBaumrock 

first of all, a great module! Thanks for that. But I also have a problem with the implementation of FieldtypeOptions. I personally have pages that have lots of option-select fields (single value select). Since each time the value is accessed, a separate SQL query is fired for it, I quickly come up with over 500 SQL queries. That's why I wanted to use your module to significantly increase the performance. The problem: RockFinder only returns the ID of the select value (which would be the same behaviour in the end when i access the value). The real value is stored in the table `fieldtype_options`. So I do not want the ID to be returned. 

I have already created a new fieldtype named "options.php" and changed that this class is used instead of the "file.php" class. But I am stuck on the JOIN. I need the `page.id` to get the right value. But neither `pages.id`, nor `pwfinder.id` or `rockfinder.id` works. Here is the current code of the class options.php. On the ??? I am stuck.

```php
<?php namespace ProcessWire;
class RockFinderFieldOptions extends RockFinderField {
  public $separator = ',';

  public function getJoin() {
    return "\n\n/* --- join $this->alias --- */\n".
      "LEFT JOIN (" . $this->getSql() . ") AS `$this->alias` ".
      "ON `$this->alias` != ''".
      "\n/* --- end $this->alias --- */\n";
  }

  public function getSql() {    

    $sql  = "SELECT";
    $sql .= "\n  `value` AS `$this->alias`";
    $sql .= "\n  FROM `fieldtype_options` ";
    $sql .= "\n  WHERE `option_id` = (";
    $sql .= "\n    SELECT `data` FROM `field_".strtolower($this->name)."` WHERE `pages_id` = ???";
    $sql .= "\n )  AND `fields_id` = (";
    $sql .= "\n    SELECT `id` FROM `fields` WHERE `name` = '$this->alias'";
    $sql .= "\n )";
    $sql .= "\nGROUP BY `value`";
    return $sql;
  }
}
```
Do you have a simple solution to get the selected value and not the ID? You would help me incredibly with that! Thank you in advance.

**Comment by BernhardBaumrock** [comment]
Hi @FlipZoomMedia Have you tried using RockFinder2 https://processwire.com/talk/topic/22205-rockfinder2-combine-the-power-of-pw-selectors-and-sql/ ?

**Comment by flipzoom** [comment]
Hi @BernhardBaumrock Thanks for your quick response. I wanted to try it first, but I can't get version 2 to work. I get the same error message as Robin in the forum (https://processwire.com/talk/topic/22205-rockfinder2-combine-the-power-of-pw-selectors-and-sql/?tab=comments#comment-196865). Latest PW-DEV version, PHP 7.3 or 7.4. I always get the Invoke error, even when using your simple examples. 

```php
$rf = new RockFinder2();
$rf->find("id>2, limit=5");
$rf->addColumns([
    'title',
    'modified'
]);
$rf->query;
db($rf->getData());
```
![screenshot-localhost-2020 04 06-16_32_24](https://user-images.githubusercontent.com/708183/78569521-0a964f00-7824-11ea-8355-d1ecf032bf09.png)

**Comment by BernhardBaumrock** [comment]
This is strange - I have no issues. I'll have a look!

**Comment by BernhardBaumrock** [comment]
Fixed in v0.0.3
I'll close this issue as RockFinder1 is really not meant to be used any more :)

**Comment by flipzoom** [comment]
Thanks @BernhardBaumrock, the problem was that the module was not loaded. :no_good: 

Nevertheless, RF2 has the same problem with the options. Only the ID is loaded and not the actual select value. Also there I do not get it implemented. :confused: And the function addOptions() does not solve the problem, because here also for each select field a query is fired and only the title is loaded and not the value. Should I open a ticket in RF2-Repo? Thank you in advance!

**Comment by BernhardBaumrock** [comment]
No, this is not an issue, this is just a different concept how to work with PW data. We are used to have the human readable values at our fingertips, but that's not performant when dealing with many datasets. You have different options how to get the proper values. How many different options do you have?

**Comment by flipzoom** [comment]
Each page has about 60 select option fields (with design settings), each of these select option fields has a different number of options, but only one or none can be selected at a time. 

If the value is accessed in the frontend with `->value`, PW respectively FieldtypeOptions generates a separate SQL query. With this amount of fields, 60 additional queries are triggered on this page. Therefore I want to use your module to get around this. :blush: Because if the real select value instead of the ID is present, all the additional queries are omitted. 

Maybe I have expressed myself wrong. Therefore I will repeat it here as a question. How do I get the direct select value from the table `fieldtype_options` instead of the ID? :blush:

**Comment by BernhardBaumrock** [comment]
I understood your question - I'm just thinking there might be a better solution for your problem than hiding an inefficient setup behind an efficient (but maybe complicated) RockFinder2 query ;)

Please write me a PM on the forum!
